name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */12 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          config_timezone: Europe/Paris
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: dockerfile, makefile
          plugin_languages_skipped: E428, That-level-again-unity
          config_order: base.header, isocalendar, languages

      - name: 💡 Coding habits (charts)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1 # Display #1 project of lowlighter/metrics repository
          plugin_projects_limit: 4                                    # Limit to 4 entries
          plugin_projects_descriptions: yes                           # Display projects descriptions
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          config_timezone: Europe/Paris
          delay: 120
          
